print("Hallo Wprld!")
my_name = input("What is your name?", )
print("It is good to meet you," + my_name)
print("The length of your name is:" + len(my_name)
age  = int(input("What is your age:" ,))
print("You will be" + str(int(age)+1)+"in a year")